AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Application:
    Description: Name of your application
    Type: String
    Default: final
  LoadbalancerArn:
    Description: Shared application lb 
    Type: String
    Default: """lb arn"""
  s3:
    Description: Name of your s3 bucket
    Type: String
    Default: demobuckxyxy
  kp:
    Description: Name of downloaded key pair
    Type: String
    Default: demo-kp
  file:
    Description: Name of zip file in s3 bucket
    Type: String
    Default: demo.zip
  environment:
    Description: Name of new Environment
    Type: String
    Default: finalenv
  
Resources:
  ElasticBeanstalkServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - elasticbeanstalk.amazonaws.com
            Action:
              - 'sts:AssumeRole' 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceProfileRole
  InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com 
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref Application
      Description: AWS ElasticBeanstalk Application Version
      SourceBundle:
        S3Bucket: !Ref s3
        S3Key: !Ref file
  
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      EnvironmentName: !Ref environment
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.23.0 running Multi-container Docker 19.03.6-ce (Generic)  
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: ServiceRole
          Value: !Ref ElasticBeanstalkServiceRole
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: !Ref kp
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: application
        - Namespace: aws:elbv2:loadbalancer
          OptionName: SharedLoadBalancer
          Value: !Ref LoadbalancerArn 
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerIsShared 
          Value: true
      VersionLabel:
        Ref: ApplicationVersion

      

